[package]
name = "ecu_diagnostics"
version = "0.8.1"
authors = ["Ashcon Mohseninia <ashconm@outlook.com>"]
edition = "2021"
description = "A rust crate for ECU diagnostic servers and communication APIs"
license = "MIT"
repository = "https://github.com/rnd-ash/ecu_diagnostics"
readme = "README.md"
keywords = ["socketcan", "kwp2000", "uds", "j2534", "dpdu"]
exclude = [
    "examples/*",
    "build.rs",
    "ecu_diagnostics.hpp"
]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "i686-pc-windows-msvc", "x86_64-apple-darwin"]

[workspace]
members = [
    "ffi",
]

[dependencies]
j2534_rust = "1.0"
serde_json = "1.0"
libloading = "0.7.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.8"

[target.'cfg(unix)'.dependencies]
shellexpand = "2.0.0"
socketcan-isotp = "0.1.1"
socketcan = "1.7.0"