[package]
name = "ecu_diagnostics"
version = "0.1.0"
authors = ["Ashcon Mohseninia <ashconm@outlook.com>"]
edition = "2018"
description = "A rust crate for ECU diagnostic servers"
license = "MIT"
repository = "https://github.com/rnd-ash/ecu_diagnostics"
readme = "README.md"

[lib]
name = "ecu_diagnostics"