[package]
name = "ecu_diagnostics"
version = "0.4.1"
authors = ["Ashcon Mohseninia <ashconm@outlook.com>"]
edition = "2018"
description = "A rust crate for ECU diagnostic servers"
license = "MIT"
repository = "https://github.com/rnd-ash/ecu_diagnostics"
readme = "README.md"
keywords = ["ecu", "kwp2000", "uds", "obd2", "cars"]
exclude = [
    "examples/*",
    "build.rs",
    "ecu_diagnostics.hpp"
]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
targets = ["i686-pc-windows-msvc", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]

[workspace]
members = [
    "examples/passthru_isotp",
    "examples/uds_over_socketcan",
    "ffi"
]

[dependencies]
j2534_rust = "1.0"
serde_json = "1.0"
libloading = "0.7.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.8"

[target.'cfg(unix)'.dependencies]
shellexpand = "2.0.0"
socketcan-isotp = "0.1.1"
socketcan = "1.7.0"