[package]
name = "uds_over_socketcan"
version = "0.1.0"
authors = ["Ashcon Mohseninia <ashconm@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
ecu_diagnostics = { path = "../../" }
socketcan-isotp = "0.1.1"